version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt_broker_local_mosquitto
    volumes:
      - ./mqtt_broker/:/mosquitto/:rw
    ports:
      - "1883:1883"
      - "9001:9001"
